coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 85%
    patch:
      default:
        target: 80%
comment:
  layout: "header, diff, tree"
  behavior: default
fixes:
  # Strip the CI build path and the mediawiki/ prefix
  - "/home/runner/work/LabkiPackManager/LabkiPackManager/mediawiki/::"
  - "mediawiki/::"
  - "extensions/LabkiPackManager/::"
